// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedDragonAPI.Data;

#nullable disable

namespace RedDragonAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260225134117_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RedDragonAPI.Models.Entities.ActiveSpell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CastAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("KingdomId")
                        .HasColumnType("int");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<string>("SpellType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("KingdomId");

                    b.HasIndex("SpellType");

                    b.ToTable("ActiveSpells");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.BattleReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttackerKingdomId")
                        .HasColumnType("int");

                    b.Property<string>("AttackerLosses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BattleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DefenderKingdomId")
                        .HasColumnType("int");

                    b.Property<string>("DefenderLosses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LandCaptured")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResourcesStolen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AttackerKingdomId");

                    b.HasIndex("DefenderKingdomId");

                    b.ToTable("BattleReports");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ConstructionCompletesAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUnderConstruction")
                        .HasColumnType("bit");

                    b.Property<int>("KingdomId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingType");

                    b.HasIndex("KingdomId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.BuildingDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BonusTurnsPerDay")
                        .HasColumnType("int");

                    b.Property<int>("BuildTime")
                        .HasColumnType("int");

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CostGold")
                        .HasColumnType("int");

                    b.Property<int>("CostIron")
                        .HasColumnType("int");

                    b.Property<int>("CostLand")
                        .HasColumnType("int");

                    b.Property<int>("CostMana")
                        .HasColumnType("int");

                    b.Property<int>("CostStone")
                        .HasColumnType("int");

                    b.Property<int>("CostWood")
                        .HasColumnType("int");

                    b.Property<decimal>("DefenseBonus")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsSpecial")
                        .HasColumnType("bit");

                    b.Property<int>("PopulationCapacity")
                        .HasColumnType("int");

                    b.Property<decimal>("ProductionBonus")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("RequiredBuildingType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequiredTechnology")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingType")
                        .IsUnique();

                    b.ToTable("BuildingDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BonusTurnsPerDay = 0,
                            BuildTime = 1,
                            BuildingType = "House",
                            Category = "Residential",
                            CostGold = 0,
                            CostIron = 0,
                            CostLand = 2,
                            CostMana = 0,
                            CostStone = 20,
                            CostWood = 50,
                            DefenseBonus = 0m,
                            Description = "Zwiększa limit ludności o 100",
                            DisplayName = "Dom",
                            IsSpecial = false,
                            PopulationCapacity = 100,
                            ProductionBonus = 0m
                        },
                        new
                        {
                            Id = 2,
                            BonusTurnsPerDay = 0,
                            BuildTime = 1,
                            BuildingType = "Farm",
                            Category = "Economic",
                            CostGold = 10,
                            CostIron = 0,
                            CostLand = 3,
                            CostMana = 0,
                            CostStone = 0,
                            CostWood = 40,
                            DefenseBonus = 0m,
                            Description = "Produkuje 500 żywności na turę",
                            DisplayName = "Farma",
                            IsSpecial = false,
                            PopulationCapacity = 0,
                            ProductionBonus = 0m
                        },
                        new
                        {
                            Id = 3,
                            BonusTurnsPerDay = 0,
                            BuildTime = 2,
                            BuildingType = "Sawmill",
                            Category = "Economic",
                            CostGold = 30,
                            CostIron = 0,
                            CostLand = 2,
                            CostMana = 0,
                            CostStone = 0,
                            CostWood = 60,
                            DefenseBonus = 0m,
                            Description = "Produkuje 300 drewna na turę",
                            DisplayName = "Tartak",
                            IsSpecial = false,
                            PopulationCapacity = 0,
                            ProductionBonus = 0m
                        },
                        new
                        {
                            Id = 4,
                            BonusTurnsPerDay = 0,
                            BuildTime = 2,
                            BuildingType = "Quarry",
                            Category = "Economic",
                            CostGold = 50,
                            CostIron = 0,
                            CostLand = 3,
                            CostMana = 0,
                            CostStone = 0,
                            CostWood = 50,
                            DefenseBonus = 0m,
                            Description = "Wydobywa kamień (wymaga kamieniarzy)",
                            DisplayName = "Kamieniołom",
                            IsSpecial = false,
                            PopulationCapacity = 0,
                            ProductionBonus = 0m
                        },
                        new
                        {
                            Id = 5,
                            BonusTurnsPerDay = 0,
                            BuildTime = 3,
                            BuildingType = "Mine",
                            Category = "Economic",
                            CostGold = 100,
                            CostIron = 0,
                            CostLand = 4,
                            CostMana = 0,
                            CostStone = 50,
                            CostWood = 100,
                            DefenseBonus = 0m,
                            Description = "Produkuje 200 żelaza na turę",
                            DisplayName = "Kopalnia",
                            IsSpecial = false,
                            PopulationCapacity = 0,
                            ProductionBonus = 0m
                        },
                        new
                        {
                            Id = 6,
                            BonusTurnsPerDay = 0,
                            BuildTime = 3,
                            BuildingType = "Forge",
                            Category = "Economic",
                            CostGold = 150,
                            CostIron = 0,
                            CostLand = 2,
                            CostMana = 0,
                            CostStone = 100,
                            CostWood = 80,
                            DefenseBonus = 0m,
                            Description = "Przekształca żelazo w broń",
                            DisplayName = "Kuźnia",
                            IsSpecial = false,
                            PopulationCapacity = 0,
                            ProductionBonus = 0m
                        },
                        new
                        {
                            Id = 7,
                            BonusTurnsPerDay = 0,
                            BuildTime = 2,
                            BuildingType = "Workshop",
                            Category = "Economic",
                            CostGold = 50,
                            CostIron = 0,
                            CostLand = 2,
                            CostMana = 0,
                            CostStone = 30,
                            CostWood = 50,
                            DefenseBonus = 0m,
                            Description = "Bonus +10% do produkcji surowców",
                            DisplayName = "Warsztat",
                            IsSpecial = false,
                            PopulationCapacity = 0,
                            ProductionBonus = 0.10m
                        },
                        new
                        {
                            Id = 8,
                            BonusTurnsPerDay = 0,
                            BuildTime = 5,
                            BuildingType = "Manufactory",
                            Category = "Economic",
                            CostGold = 500,
                            CostIron = 0,
                            CostLand = 4,
                            CostMana = 0,
                            CostStone = 200,
                            CostWood = 150,
                            DefenseBonus = 0m,
                            Description = "Bonus +20% do produkcji zaawansowanej",
                            DisplayName = "Manufaktura",
                            IsSpecial = false,
                            PopulationCapacity = 0,
                            ProductionBonus = 0.20m,
                            RequiredBuildingType = "Workshop"
                        },
                        new
                        {
                            Id = 9,
                            BonusTurnsPerDay = 0,
                            BuildTime = 5,
                            BuildingType = "University",
                            Category = "Scientific",
                            CostGold = 1000,
                            CostIron = 0,
                            CostLand = 5,
                            CostMana = 0,
                            CostStone = 300,
                            CostWood = 200,
                            DefenseBonus = 0m,
                            Description = "Umożliwia badania technologiczne",
                            DisplayName = "Uniwersytet",
                            IsSpecial = false,
                            PopulationCapacity = 0,
                            ProductionBonus = 0m
                        },
                        new
                        {
                            Id = 10,
                            BonusTurnsPerDay = 0,
                            BuildTime = 3,
                            BuildingType = "Barracks",
                            Category = "Military",
                            CostGold = 300,
                            CostIron = 0,
                            CostLand = 3,
                            CostMana = 0,
                            CostStone = 150,
                            CostWood = 150,
                            DefenseBonus = 0m,
                            Description = "Szkolenie piechoty",
                            DisplayName = "Koszary",
                            IsSpecial = false,
                            PopulationCapacity = 0,
                            ProductionBonus = 0m
                        },
                        new
                        {
                            Id = 11,
                            BonusTurnsPerDay = 0,
                            BuildTime = 3,
                            BuildingType = "ArcheryRange",
                            Category = "Military",
                            CostGold = 250,
                            CostIron = 0,
                            CostLand = 3,
                            CostMana = 0,
                            CostStone = 80,
                            CostWood = 120,
                            DefenseBonus = 0m,
                            Description = "Szkolenie łuczników",
                            DisplayName = "Strzelnica",
                            IsSpecial = false,
                            PopulationCapacity = 0,
                            ProductionBonus = 0m
                        },
                        new
                        {
                            Id = 12,
                            BonusTurnsPerDay = 0,
                            BuildTime = 4,
                            BuildingType = "Stable",
                            Category = "Military",
                            CostGold = 500,
                            CostIron = 0,
                            CostLand = 4,
                            CostMana = 0,
                            CostStone = 150,
                            CostWood = 200,
                            DefenseBonus = 0m,
                            Description = "Szkolenie kawalerii",
                            DisplayName = "Stajnia",
                            IsSpecial = false,
                            PopulationCapacity = 0,
                            ProductionBonus = 0m
                        },
                        new
                        {
                            Id = 13,
                            BonusTurnsPerDay = 0,
                            BuildTime = 2,
                            BuildingType = "Wall",
                            Category = "Defensive",
                            CostGold = 200,
                            CostIron = 0,
                            CostLand = 1,
                            CostMana = 0,
                            CostStone = 100,
                            CostWood = 0,
                            DefenseBonus = 0.05m,
                            Description = "Bonus obronny +5% per poziom (max 10)",
                            DisplayName = "Mur",
                            IsSpecial = false,
                            PopulationCapacity = 0,
                            ProductionBonus = 0m
                        },
                        new
                        {
                            Id = 14,
                            BonusTurnsPerDay = 0,
                            BuildTime = 3,
                            BuildingType = "GuardTower",
                            Category = "Defensive",
                            CostGold = 300,
                            CostIron = 0,
                            CostLand = 2,
                            CostMana = 0,
                            CostStone = 150,
                            CostWood = 0,
                            DefenseBonus = 0.03m,
                            Description = "Bonus obronny +3%, wykrywa złodziei +10%",
                            DisplayName = "Wieża Strażnicza",
                            IsSpecial = false,
                            PopulationCapacity = 0,
                            ProductionBonus = 0m
                        },
                        new
                        {
                            Id = 15,
                            BonusTurnsPerDay = 0,
                            BuildTime = 10,
                            BuildingType = "EnchantmentPoint",
                            Category = "Defensive",
                            CostGold = 1000,
                            CostIron = 0,
                            CostLand = 3,
                            CostMana = 500,
                            CostStone = 500,
                            CostWood = 0,
                            DefenseBonus = 0m,
                            Description = "Nie może być zniszczony magią ani złodziejami",
                            DisplayName = "Punkt Zaklinania (PZ)",
                            IsSpecial = false,
                            PopulationCapacity = 0,
                            ProductionBonus = 0m
                        },
                        new
                        {
                            Id = 16,
                            BonusTurnsPerDay = 1,
                            BuildTime = 10,
                            BuildingType = "MerchantGuild",
                            Category = "Special",
                            CostGold = 10000,
                            CostIron = 0,
                            CostLand = 5,
                            CostMana = 0,
                            CostStone = 5000,
                            CostWood = 0,
                            DefenseBonus = 0m,
                            Description = "Bonus +50% złota od kupców, +1 tura/dzień",
                            DisplayName = "Gildia Kupców",
                            IsSpecial = true,
                            PopulationCapacity = 0,
                            ProductionBonus = 0.50m
                        },
                        new
                        {
                            Id = 17,
                            BonusTurnsPerDay = 1,
                            BuildTime = 10,
                            BuildingType = "MagicLibrary",
                            Category = "Special",
                            CostGold = 10000,
                            CostIron = 0,
                            CostLand = 5,
                            CostMana = 2000,
                            CostStone = 5000,
                            CostWood = 0,
                            DefenseBonus = 0m,
                            Description = "Bonus +50% produkcji many, +1 tura/dzień",
                            DisplayName = "Biblioteka Magiczna",
                            IsSpecial = true,
                            PopulationCapacity = 0,
                            ProductionBonus = 0.50m
                        },
                        new
                        {
                            Id = 18,
                            BonusTurnsPerDay = 1,
                            BuildTime = 10,
                            BuildingType = "MilitaryAcademy",
                            Category = "Special",
                            CostGold = 10000,
                            CostIron = 2000,
                            CostLand = 5,
                            CostMana = 0,
                            CostStone = 5000,
                            CostWood = 0,
                            DefenseBonus = 0m,
                            Description = "Bonus +20% siły armii, +1 tura/dzień",
                            DisplayName = "Akademia Wojskowa",
                            IsSpecial = true,
                            PopulationCapacity = 0,
                            ProductionBonus = 0m
                        },
                        new
                        {
                            Id = 19,
                            BonusTurnsPerDay = 1,
                            BuildTime = 10,
                            BuildingType = "ThievesGuild",
                            Category = "Special",
                            CostGold = 10000,
                            CostIron = 0,
                            CostLand = 5,
                            CostMana = 0,
                            CostStone = 5000,
                            CostWood = 0,
                            DefenseBonus = 0m,
                            Description = "Bonus +30% skuteczności złodziei, +1 tura/dzień",
                            DisplayName = "Gildia Złodziei",
                            IsSpecial = true,
                            PopulationCapacity = 0,
                            ProductionBonus = 0m
                        },
                        new
                        {
                            Id = 20,
                            BonusTurnsPerDay = 2,
                            BuildTime = 15,
                            BuildingType = "Citadel",
                            Category = "Special",
                            CostGold = 15000,
                            CostIron = 3000,
                            CostLand = 8,
                            CostMana = 0,
                            CostStone = 10000,
                            CostWood = 0,
                            DefenseBonus = 0.50m,
                            Description = "Bonus +50% obrony, +2 tury/dzień",
                            DisplayName = "Cytadela",
                            IsSpecial = true,
                            PopulationCapacity = 0,
                            ProductionBonus = 0m
                        });
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.Coalition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EraId")
                        .HasColumnType("int");

                    b.Property<int?>("LeaderKingdomId")
                        .HasColumnType("int");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PSOProgress")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Tag")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("EraId");

                    b.HasIndex("LeaderKingdomId");

                    b.ToTable("Coalitions");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.Era", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Theme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WinningCoalitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WinningCoalitionId");

                    b.ToTable("Eras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Era Przebudzenia",
                            StartedAt = new DateTime(2026, 2, 25, 13, 41, 17, 327, DateTimeKind.Utc).AddTicks(3060),
                            Theme = "Pierwsza era nowego świata Red Dragon"
                        });
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.Kingdom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("CoalitionId")
                        .HasColumnType("int");

                    b.Property<string>("CoalitionRole")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EraId")
                        .HasColumnType("int");

                    b.Property<long>("Food")
                        .HasColumnType("bigint");

                    b.Property<long>("Gold")
                        .HasColumnType("bigint");

                    b.Property<long>("Iron")
                        .HasColumnType("bigint");

                    b.Property<int>("Land")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("datetime2");

                    b.Property<long>("Mana")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxTurns")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.Property<int>("PopulationGrowthRate")
                        .HasColumnType("int");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("Stone")
                        .HasColumnType("bigint");

                    b.Property<int>("TurnsAvailable")
                        .HasColumnType("int");

                    b.Property<int>("TurnsPerDay")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<long>("Wood")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CoalitionId");

                    b.HasIndex("EraId");

                    b.HasIndex("UserId");

                    b.ToTable("Kingdoms");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("ReceiverKingdomId")
                        .HasColumnType("int");

                    b.Property<int>("SenderKingdomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverKingdomId");

                    b.HasIndex("SenderKingdomId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.MilitaryUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InTraining")
                        .HasColumnType("int");

                    b.Property<int>("KingdomId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TrainingCompletesAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("KingdomId");

                    b.HasIndex("UnitType");

                    b.ToTable("MilitaryUnits");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.Pantheon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoalitionId")
                        .HasColumnType("int");

                    b.Property<int>("EraId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VictoryDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CoalitionId");

                    b.HasIndex("EraId", "CoalitionId")
                        .IsUnique();

                    b.ToTable("Pantheon");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.Profession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KingdomId")
                        .HasColumnType("int");

                    b.Property<long>("ProductionPerTurn")
                        .HasColumnType("bigint");

                    b.Property<string>("ProfessionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WorkerCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KingdomId", "ProfessionType")
                        .IsUnique();

                    b.ToTable("Professions");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.QueuedAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("KingdomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledFor")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TargetKingdomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KingdomId");

                    b.HasIndex("TargetKingdomId");

                    b.HasIndex("ScheduledFor", "Status");

                    b.ToTable("QueuedActions");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.Research", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletesAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInProgress")
                        .HasColumnType("bit");

                    b.Property<int>("KingdomId")
                        .HasColumnType("int");

                    b.Property<string>("TechType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TechType");

                    b.HasIndex("KingdomId", "TechType")
                        .IsUnique();

                    b.ToTable("Research");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.SpellDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EffectType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ManaCost")
                        .HasColumnType("int");

                    b.Property<int>("PowerLevel")
                        .HasColumnType("int");

                    b.Property<string>("SpellType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TargetType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SpellType")
                        .IsUnique();

                    b.ToTable("SpellDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "White",
                            Description = "Leczy rany żołnierzy po walce",
                            DisplayName = "Światło Uzdrowienia",
                            EffectType = "Buff",
                            ManaCost = 100,
                            PowerLevel = 5,
                            SpellType = "HealingLight",
                            TargetType = "Self"
                        },
                        new
                        {
                            Id = 2,
                            Category = "White",
                            Description = "+15% obrony na 5 tur",
                            DisplayName = "Aura Ochronna",
                            EffectType = "Buff",
                            ManaCost = 200,
                            PowerLevel = 10,
                            SpellType = "ProtectiveAura",
                            TargetType = "Self"
                        },
                        new
                        {
                            Id = 3,
                            Category = "White",
                            Description = "+25% produkcji na 3 tury",
                            DisplayName = "Błogosławieństwo Produkcji",
                            EffectType = "Buff",
                            ManaCost = 150,
                            PowerLevel = 8,
                            SpellType = "ProductionBlessing",
                            TargetType = "Self"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Destructive",
                            Description = "Zadaje obrażenia armii wroga",
                            DisplayName = "Kula Ognia",
                            EffectType = "Damage",
                            ManaCost = 300,
                            PowerLevel = 15,
                            SpellType = "Fireball",
                            TargetType = "Enemy"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Destructive",
                            Description = "Niszczy budynki wroga",
                            DisplayName = "Trzęsienie Ziemi",
                            EffectType = "Damage",
                            ManaCost = 500,
                            PowerLevel = 20,
                            SpellType = "Earthquake",
                            TargetType = "Enemy"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Black",
                            Description = "Zmniejsza populację wroga",
                            DisplayName = "Zaraza",
                            EffectType = "Debuff",
                            ManaCost = 400,
                            PowerLevel = 18,
                            SpellType = "Plague",
                            TargetType = "Enemy"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Black",
                            Description = "-20% produkcji wroga na 5 tur",
                            DisplayName = "Klątwa",
                            EffectType = "Debuff",
                            ManaCost = 250,
                            PowerLevel = 12,
                            SpellType = "Curse",
                            TargetType = "Enemy"
                        });
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.TechnologyDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CostGold")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EffectType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("EffectValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("RequiredBuilding")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequiredTech")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ResearchTime")
                        .HasColumnType("int");

                    b.Property<string>("TechType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TechType")
                        .IsUnique();

                    b.ToTable("TechnologyDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Economy",
                            CostGold = 5000,
                            Description = "+20% produkcji żywności",
                            DisplayName = "Rolnictwo I",
                            EffectType = "FoodProduction",
                            EffectValue = 0.20m,
                            Level = 1,
                            ResearchTime = 10,
                            TechType = "AgricultureI"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Economy",
                            CostGold = 15000,
                            Description = "+40% produkcji żywności",
                            DisplayName = "Rolnictwo II",
                            EffectType = "FoodProduction",
                            EffectValue = 0.40m,
                            Level = 1,
                            RequiredTech = "AgricultureI",
                            ResearchTime = 20,
                            TechType = "AgricultureII"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Economy",
                            CostGold = 40000,
                            Description = "+60% produkcji żywności",
                            DisplayName = "Rolnictwo III",
                            EffectType = "FoodProduction",
                            EffectValue = 0.60m,
                            Level = 1,
                            RequiredTech = "AgricultureII",
                            ResearchTime = 30,
                            TechType = "AgricultureIII"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Economy",
                            CostGold = 5000,
                            Description = "+20% produkcji kamienia i żelaza",
                            DisplayName = "Górnictwo I",
                            EffectType = "MiningProduction",
                            EffectValue = 0.20m,
                            Level = 1,
                            ResearchTime = 10,
                            TechType = "MiningI"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Economy",
                            CostGold = 15000,
                            Description = "+40% produkcji kamienia i żelaza",
                            DisplayName = "Górnictwo II",
                            EffectType = "MiningProduction",
                            EffectValue = 0.40m,
                            Level = 1,
                            RequiredTech = "MiningI",
                            ResearchTime = 20,
                            TechType = "MiningII"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Economy",
                            CostGold = 40000,
                            Description = "+60% produkcji kamienia i żelaza",
                            DisplayName = "Górnictwo III",
                            EffectType = "MiningProduction",
                            EffectValue = 0.60m,
                            Level = 1,
                            RequiredTech = "MiningII",
                            ResearchTime = 30,
                            TechType = "MiningIII"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Military",
                            CostGold = 10000,
                            Description = "+15% siły ataku",
                            DisplayName = "Broń I",
                            EffectType = "AttackBonus",
                            EffectValue = 0.15m,
                            Level = 1,
                            ResearchTime = 15,
                            TechType = "WeaponryI"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Military",
                            CostGold = 25000,
                            Description = "+30% siły ataku",
                            DisplayName = "Broń II",
                            EffectType = "AttackBonus",
                            EffectValue = 0.30m,
                            Level = 1,
                            RequiredTech = "WeaponryI",
                            ResearchTime = 25,
                            TechType = "WeaponryII"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Military",
                            CostGold = 50000,
                            Description = "+50% siły ataku",
                            DisplayName = "Broń III",
                            EffectType = "AttackBonus",
                            EffectValue = 0.50m,
                            Level = 1,
                            RequiredTech = "WeaponryII",
                            ResearchTime = 35,
                            TechType = "WeaponryIII"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Military",
                            CostGold = 10000,
                            Description = "+15% obrony",
                            DisplayName = "Zbroja I",
                            EffectType = "DefenseBonus",
                            EffectValue = 0.15m,
                            Level = 1,
                            ResearchTime = 15,
                            TechType = "ArmorI"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Military",
                            CostGold = 25000,
                            Description = "+30% obrony",
                            DisplayName = "Zbroja II",
                            EffectType = "DefenseBonus",
                            EffectValue = 0.30m,
                            Level = 1,
                            RequiredTech = "ArmorI",
                            ResearchTime = 25,
                            TechType = "ArmorII"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Military",
                            CostGold = 50000,
                            Description = "+50% obrony",
                            DisplayName = "Zbroja III",
                            EffectType = "DefenseBonus",
                            EffectValue = 0.50m,
                            Level = 1,
                            RequiredTech = "ArmorII",
                            ResearchTime = 35,
                            TechType = "ArmorIII"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Magic",
                            CostGold = 8000,
                            Description = "+20% efektywności bufów",
                            DisplayName = "Biała Magia I",
                            EffectType = "BuffPower",
                            EffectValue = 0.20m,
                            Level = 1,
                            ResearchTime = 12,
                            TechType = "WhiteMagicI"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Magic",
                            CostGold = 20000,
                            Description = "+40% efektywności bufów",
                            DisplayName = "Biała Magia II",
                            EffectType = "BuffPower",
                            EffectValue = 0.40m,
                            Level = 1,
                            RequiredTech = "WhiteMagicI",
                            ResearchTime = 22,
                            TechType = "WhiteMagicII"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Magic",
                            CostGold = 12000,
                            Description = "+15% siły czarów bojowych",
                            DisplayName = "Magia Niszcząca I",
                            EffectType = "SpellPower",
                            EffectValue = 0.15m,
                            Level = 1,
                            ResearchTime = 18,
                            TechType = "DestructiveMagicI"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Magic",
                            CostGold = 30000,
                            Description = "+30% siły czarów bojowych",
                            DisplayName = "Magia Niszcząca II",
                            EffectType = "SpellPower",
                            EffectValue = 0.30m,
                            Level = 1,
                            RequiredTech = "DestructiveMagicI",
                            ResearchTime = 28,
                            TechType = "DestructiveMagicII"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Magic",
                            CostGold = 60000,
                            Description = "+50% siły czarów bojowych",
                            DisplayName = "Magia Niszcząca III",
                            EffectType = "SpellPower",
                            EffectValue = 0.50m,
                            Level = 1,
                            RequiredTech = "DestructiveMagicII",
                            ResearchTime = 38,
                            TechType = "DestructiveMagicIII"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Thieves",
                            CostGold = 7000,
                            Description = "+20% skuteczności kradzieży",
                            DisplayName = "Skradanie I",
                            EffectType = "ThiefSuccess",
                            EffectValue = 0.20m,
                            Level = 1,
                            ResearchTime = 10,
                            TechType = "StealthI"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Thieves",
                            CostGold = 18000,
                            Description = "+40% skuteczności kradzieży",
                            DisplayName = "Skradanie II",
                            EffectType = "ThiefSuccess",
                            EffectValue = 0.40m,
                            Level = 1,
                            RequiredTech = "StealthI",
                            ResearchTime = 20,
                            TechType = "StealthII"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Thieves",
                            CostGold = 15000,
                            Description = "Umożliwia szpiegowanie wrogów",
                            DisplayName = "Szpiegostwo",
                            EffectType = "UnlockEspionage",
                            EffectValue = 1.0m,
                            Level = 1,
                            RequiredTech = "StealthI",
                            ResearchTime = 15,
                            TechType = "Espionage"
                        });
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.ThiefActionDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EffectType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SuccessBaseRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ThievesRequired")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActionType")
                        .IsUnique();

                    b.ToTable("ThiefActionDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionType = "StealGold",
                            Description = "Kradnie złoto z wrogiego skarbca",
                            DisplayName = "Kradzież Złota",
                            EffectType = "StealGold",
                            SuccessBaseRate = 0.60m,
                            ThievesRequired = 50
                        },
                        new
                        {
                            Id = 2,
                            ActionType = "StealResources",
                            Description = "Kradnie surowce wroga",
                            DisplayName = "Kradzież Surowców",
                            EffectType = "StealResources",
                            SuccessBaseRate = 0.50m,
                            ThievesRequired = 75
                        },
                        new
                        {
                            Id = 3,
                            ActionType = "Sabotage",
                            Description = "Niszczy budynki wroga",
                            DisplayName = "Sabotaż",
                            EffectType = "Sabotage",
                            SuccessBaseRate = 0.40m,
                            ThievesRequired = 100
                        },
                        new
                        {
                            Id = 4,
                            ActionType = "Spy",
                            Description = "Zbiera informacje o wrogu",
                            DisplayName = "Szpiegostwo",
                            EffectType = "Spy",
                            SuccessBaseRate = 0.70m,
                            ThievesRequired = 30
                        },
                        new
                        {
                            Id = 5,
                            ActionType = "Assassination",
                            Description = "Zabija magów lub naukowców wroga",
                            DisplayName = "Zamach",
                            EffectType = "Sabotage",
                            SuccessBaseRate = 0.30m,
                            ThievesRequired = 150
                        });
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.UnitDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttackPower")
                        .HasColumnType("int");

                    b.Property<int>("CostFood")
                        .HasColumnType("int");

                    b.Property<int>("CostGold")
                        .HasColumnType("int");

                    b.Property<int>("CostIron")
                        .HasColumnType("int");

                    b.Property<int>("CostWood")
                        .HasColumnType("int");

                    b.Property<int>("DefensePower")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RequiredBuilding")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequiredTech")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrainingTime")
                        .HasColumnType("int");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Upkeep")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnitType", "Race")
                        .IsUnique();

                    b.ToTable("UnitDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttackPower = 10,
                            CostFood = 10,
                            CostGold = 50,
                            CostIron = 20,
                            CostWood = 0,
                            DefensePower = 12,
                            Description = "Podstawowe jednostki piechoty",
                            DisplayName = "Piechota",
                            Race = "Human",
                            RequiredBuilding = "Barracks",
                            TrainingTime = 1,
                            UnitType = "Infantry",
                            Upkeep = 2
                        },
                        new
                        {
                            Id = 2,
                            AttackPower = 15,
                            CostFood = 10,
                            CostGold = 80,
                            CostIron = 15,
                            CostWood = 30,
                            DefensePower = 6,
                            Description = "Jednostki dystansowe",
                            DisplayName = "Łucznik",
                            Race = "Human",
                            RequiredBuilding = "ArcheryRange",
                            TrainingTime = 1,
                            UnitType = "Archer",
                            Upkeep = 3
                        },
                        new
                        {
                            Id = 3,
                            AttackPower = 25,
                            CostFood = 20,
                            CostGold = 200,
                            CostIron = 40,
                            CostWood = 0,
                            DefensePower = 20,
                            Description = "Szybkie i silne jednostki konne",
                            DisplayName = "Kawaleria",
                            Race = "Human",
                            RequiredBuilding = "Stable",
                            TrainingTime = 2,
                            UnitType = "Cavalry",
                            Upkeep = 5
                        },
                        new
                        {
                            Id = 4,
                            AttackPower = 50,
                            CostFood = 0,
                            CostGold = 500,
                            CostIron = 100,
                            CostWood = 200,
                            DefensePower = 5,
                            Description = "Bonus +100% vs budynki",
                            DisplayName = "Machina Oblężnicza",
                            Race = "Human",
                            RequiredBuilding = "Forge",
                            TrainingTime = 3,
                            UnitType = "SiegeEngine",
                            Upkeep = 10
                        },
                        new
                        {
                            Id = 5,
                            AttackPower = 50,
                            CostFood = 50,
                            CostGold = 1000,
                            CostIron = 200,
                            CostWood = 0,
                            DefensePower = 45,
                            Description = "Elitarne jednostki wojskowe",
                            DisplayName = "Rycerz",
                            Race = "Human",
                            RequiredBuilding = "MilitaryAcademy",
                            RequiredTech = "WeaponryIII",
                            TrainingTime = 5,
                            UnitType = "Knight",
                            Upkeep = 15
                        });
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.ActiveSpell", b =>
                {
                    b.HasOne("RedDragonAPI.Models.Entities.Kingdom", "Kingdom")
                        .WithMany("ActiveSpells")
                        .HasForeignKey("KingdomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RedDragonAPI.Models.Entities.SpellDefinition", "Spell")
                        .WithMany()
                        .HasForeignKey("SpellType")
                        .HasPrincipalKey("SpellType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kingdom");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.BattleReport", b =>
                {
                    b.HasOne("RedDragonAPI.Models.Entities.Kingdom", "AttackerKingdom")
                        .WithMany()
                        .HasForeignKey("AttackerKingdomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RedDragonAPI.Models.Entities.Kingdom", "DefenderKingdom")
                        .WithMany()
                        .HasForeignKey("DefenderKingdomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttackerKingdom");

                    b.Navigation("DefenderKingdom");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.Building", b =>
                {
                    b.HasOne("RedDragonAPI.Models.Entities.BuildingDefinition", "Definition")
                        .WithMany()
                        .HasForeignKey("BuildingType")
                        .HasPrincipalKey("BuildingType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RedDragonAPI.Models.Entities.Kingdom", "Kingdom")
                        .WithMany("Buildings")
                        .HasForeignKey("KingdomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definition");

                    b.Navigation("Kingdom");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.Coalition", b =>
                {
                    b.HasOne("RedDragonAPI.Models.Entities.Era", "Era")
                        .WithMany("Coalitions")
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RedDragonAPI.Models.Entities.Kingdom", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderKingdomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Era");

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.Era", b =>
                {
                    b.HasOne("RedDragonAPI.Models.Entities.Coalition", "WinningCoalition")
                        .WithMany()
                        .HasForeignKey("WinningCoalitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WinningCoalition");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.Kingdom", b =>
                {
                    b.HasOne("RedDragonAPI.Models.Entities.Coalition", "Coalition")
                        .WithMany("Members")
                        .HasForeignKey("CoalitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RedDragonAPI.Models.Entities.Era", "Era")
                        .WithMany("Kingdoms")
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RedDragonAPI.Models.Entities.User", "User")
                        .WithMany("Kingdoms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coalition");

                    b.Navigation("Era");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.Message", b =>
                {
                    b.HasOne("RedDragonAPI.Models.Entities.Kingdom", "ReceiverKingdom")
                        .WithMany()
                        .HasForeignKey("ReceiverKingdomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RedDragonAPI.Models.Entities.Kingdom", "SenderKingdom")
                        .WithMany()
                        .HasForeignKey("SenderKingdomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReceiverKingdom");

                    b.Navigation("SenderKingdom");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.MilitaryUnit", b =>
                {
                    b.HasOne("RedDragonAPI.Models.Entities.Kingdom", "Kingdom")
                        .WithMany("MilitaryUnits")
                        .HasForeignKey("KingdomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RedDragonAPI.Models.Entities.UnitDefinition", "Definition")
                        .WithMany()
                        .HasForeignKey("UnitType")
                        .HasPrincipalKey("UnitType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Definition");

                    b.Navigation("Kingdom");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.Pantheon", b =>
                {
                    b.HasOne("RedDragonAPI.Models.Entities.Coalition", "Coalition")
                        .WithMany()
                        .HasForeignKey("CoalitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RedDragonAPI.Models.Entities.Era", "Era")
                        .WithMany()
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coalition");

                    b.Navigation("Era");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.Profession", b =>
                {
                    b.HasOne("RedDragonAPI.Models.Entities.Kingdom", "Kingdom")
                        .WithMany("Professions")
                        .HasForeignKey("KingdomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kingdom");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.QueuedAction", b =>
                {
                    b.HasOne("RedDragonAPI.Models.Entities.Kingdom", "Kingdom")
                        .WithMany()
                        .HasForeignKey("KingdomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RedDragonAPI.Models.Entities.Kingdom", "TargetKingdom")
                        .WithMany()
                        .HasForeignKey("TargetKingdomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Kingdom");

                    b.Navigation("TargetKingdom");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.Research", b =>
                {
                    b.HasOne("RedDragonAPI.Models.Entities.Kingdom", "Kingdom")
                        .WithMany("Researches")
                        .HasForeignKey("KingdomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RedDragonAPI.Models.Entities.TechnologyDefinition", "Tech")
                        .WithMany()
                        .HasForeignKey("TechType")
                        .HasPrincipalKey("TechType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kingdom");

                    b.Navigation("Tech");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.Coalition", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.Era", b =>
                {
                    b.Navigation("Coalitions");

                    b.Navigation("Kingdoms");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.Kingdom", b =>
                {
                    b.Navigation("ActiveSpells");

                    b.Navigation("Buildings");

                    b.Navigation("MilitaryUnits");

                    b.Navigation("Professions");

                    b.Navigation("Researches");
                });

            modelBuilder.Entity("RedDragonAPI.Models.Entities.User", b =>
                {
                    b.Navigation("Kingdoms");
                });
#pragma warning restore 612, 618
        }
    }
}
